name: Publish
on:
  push:
    branches: [master]
jobs:
  publish:
    name: Publish
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-node@v1
      with:
        node-version: '12.x'
    - name: Install
      run: yarn install
    - name: Publish
      # https://github.com/release-it/release-it/blob/master/docs/ci.md
      run: |
        git remote rm origin
        git remote add origin https://NullVoxPopuli:${GITHUB_TOKEN}@github.com/NullVoxPopuli/ember-app.git
        # git symbolic-ref HEAD refs/heads/master


        echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > .npmrc

        set +e

        increment=$(node increment.js)
        result=$?
        echo $increment;

        if [ "$result" == "0" ]; then
          yarn release $increment;
        fi

